openapi: 3.0.0
info:
  title: Simple API
  description: A simple example API to fetch users.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /users:
    get:
      summary: Get a list of users
      description: This endpoint returns a list of users in the system.
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "user1"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "user1"
